id: IA61343A9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T19:05:38+00:00'
last_modified: '2022-06-08T17:08:04.922894+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30294
  title: སྙན་ངག་གི་དཔེར་བརྗོད་ཚངས་སྲས་དགྱེས་པའི་རོལ་མོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FA54:
      image_group_id: I6042
      title: ''
      total_pages: 702
      order: 1
      base_file: FA54.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
