id: P010733
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30294
  title: སྙན་ངག་གི་དཔེར་བརྗོད་ཚངས་སྲས་དགྱེས་པའི་རོལ་མོ
  author: ''
  volumes:
    446cef272fb6425aa9fff53fa9c557a4:
      image_group_id: I6042
      title: ''
      volume_number: 1
      total_pages: 702
      base_file: v001.txt
